/**
 * @description       : 
 * @author            : salesforce
 * @group             : gaurp
 * @last modified on  : 04-02-2025
 * @last modified by  : salesforce
**/
public class DisplayYoutubeResults {
    @AuraEnabled
	public String publishedAt;
    @AuraEnabled
	public String channelId;
	@AuraEnabled
    public String title;
	@AuraEnabled
    public String description;
	@AuraEnabled
    public String channelTitle;
	@AuraEnabled
    public String liveBroadcastContent;	
	@AuraEnabled
    public String publishTime;
}