name: Salesforce Deployment Process
run-name: ${{ github.actor }} - is running the Dev Deployment
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - Dev
    paths:
      - 'force-app/**'
    types:
      - opened
      - synchronize
      - closed
jobs:
  build:
    name: Build Salesforce PgProject Application - Developer Environment
    uses: "./.github/workflows/Template.yml"
    with:
      envValue: Dev
      BRANCH_NAME: Dev
    secrets: inherit
      #ENCRYPTED_KEY_FILE_WITH_IN_PATH: ${{ secrets.ENCRYPTED_KEY_FILE_WITH_IN_PATH }}