name: Salesforce Deployment Process
run-name: ${{ github.actor }} - is running the Prod Deployment
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - qa
      - QA
    paths:
      - 'force-app/**'
    types:
      - opened
      - synchronize
      - closed
jobs:
  build:
    name: Build Salesforce PgProject Application
    uses: "./.github/workflows/Template.yml"
    with:
      envValue: Prod
      BRANCH_NAME: Prod
    secrets: inherit
      #ENCRYPTED_KEY_FILE_WITH_IN_PATH: ${{ secrets.ENCRYPTED_KEY_FILE_WITH_IN_PATH }}