name: Salesforce Deployment Process
on:
  pull_request:
    type: [opened, synchronize, reopened]
    branches:
      - master
      - dev
      - QA
      - PreProd
      - 'feature/PGP-0002'
  push:
    branches:
      - master
      - dev
      - QA
      - PreProd
      - '*feature/**'
jobs:
  
  PreInstallations:
    environment: Dev
    name: Install Pre-Requiste Salesforce CLI and Code Analyzer Tool
    runs-on: ubuntu-latest
    steps:
      - name: PgProject Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Salesforce CLI Command
        run: |
          echo "Installing Salesforce CLI - npm install -g @salesforce/cli"
          sudo apt-get update
          npm install -g @salesforce/cli
          sf update
      - name: Install Salesforce Code Analyzer Tool
        run: |
          echo "Installing Salesforce Code Analyzer Tool - npm install -g @salesforce/sfdx-scanner"
          sf plugins install @salesforce/sfdx-scanner
      - name: Upgrade Salesforce Anyalzer Tool to Latest Version
        run: |
          echo "Upgrading Salesforce Code Analyzer Tool - npm update -g @salesforce/sfdx-scanner"
          sf plugins update -v
          echo  ${{ github.event_name }} - ${{ github.ref }}
  Build:
    environment: feature/PGP-0002
    needs: [PreInstallations]
    name: Build Salesforce PgProject Application
    runs-on: ubuntu-latest
    steps:
      - name: PgProject Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Salesforce CLI Command
        run: |
          echo "Installing Salesforce CLI - npm install -g @salesforce/cli"
          sudo apt-get update
          npm install -g @salesforce/cli
          sf update
      - name: Decrypt JWT Token for Salesforce Org
        run: |
          echo "Decrypting JWT Token for Salesforce Org"
          openssl enc -nosalt -aes-256-cbc -d -in ./assets/Dev/server_dev.key.enc -out ./assets/Dev/server_dev.key -base64 -K 043DF42C633061B51B565D8B44B9BE0471418F1BC6657F11871D0CC2EF691D2F -iv F12DDDEAB2025762BE15F4B22818466